### PR TITLE
T1 leader selection api

### LINKED ISSUE #2: T1: Leader Election Interface
(Parent task)
T1. We will define an interface, in Solidity, for a batch inbox that supports leader election strategies. This interface will be reasonably thought out, but could be updated before the final delivery, based on discoveries during implementation of the remainder of this proposal. We will include calls for checking if an address or this instance is eligible to submit batches during the current round, and possibly for checking whether the same address has a known span in which it will be, ending at or after the current round, and returning that span if it does.

- [x] Implement solidity interface. Pseudo code in https://docs.google.com/document/d/1rWDLWq4tf0APn7xLSegfGLmHYCp0qI8WjCRQh2n83g8/edit
- [x] Make sure test suite is passing

### PR DESCRIPTION
**Pull request by philippecamacho**
Proposal for an API describing how a leader is selected.
This proposal is slightly different from the one in https://docs.google.com/document/d/1rWDLWq4tf0APn7xLSegfGLmHYCp0qI8WjCRQh2n83g8/edit 
Instead of returning a range of consecutive blocks where the caller of the function is the leader, a bitmap 
encoding the positions as a leader is returned. This allows to handle more arbitrary strategies.

Closes #2 .

### CODE REVIEW

**Review by nyospe — COMMENTED** [review]
This is an improvement when the number of sequencers is small, but perhaps not when the number is large. Still, only needing to check every 32 blocks isn't terrible.

There are a few things I'd like to consider.

First, I think we have cases where we want to be able to call it *with* a leader ID to support checking by other L2s, so we need a with_id field defaulting to self.

Second, those calls may be performed at a time other than the one they need to be checked against, so we want a for_block field, defaulting to now.

Third, if we're going to have `nextBlocksAsLeader(...)` returning a series, we won't be able to provide results for more than 32 blocks in the future. This is probably fine, but should be documented, and if the intent is to only provide this for the next N<32 blocks, that should also be documented.

We can discuss tomorrow.

**Comment by philippecamacho** [comment]
Yes, I agree with all the above. The API has been updated accordingly in 3e4d211b702c47ed75f2f7716873c77761d08624. Note that using uint256 we can encode 256 positions, if we need more we can return an array of uint256.

**Comment by philippecamacho** [comment]
Also I think that if we want to implement some more advanced leader election scheme involving cryptographic proofs such as [Irish Coffee](https://discourse.aztec.network/t/proposal-sequencer-selection-irish-coffee/483) we will need some extra input to the function `isCurrentLeader`. 

**Note that in the case of a proposal like Irish Coffee, the function needs to be stateful due to race conditions.**

**Review by nyospe — APPROVED** [review]
Thanks. I think this is good enough to start with, but I agree that we will need to figure out how to extend it for more complex schemes.

**Review by nyospe — APPROVED** [review]
LGTM

**Pull request merged**
