### PR TITLE
Add flake.nix

### PR DESCRIPTION
**Pull request by sveitser**
Activate with `nix-shell` or  `nix develop`. I can successfully run `make` and `make test-unit` using this flake.

### CODE REVIEW

**Comment by philippecamacho** [comment]
Everything looks good, however the tests
* ` nx run @eth-optimism/fee-estimation:test`
*  `nx run @eth-optimism/contracts-ts:test`

are taking a long time (still running after 30min)

**Comment by sveitser** [comment]
Some `forge test` commands seem to take a really long time on my macbook too.

**Comment by philippecamacho** [comment]
> Some `forge test` commands seem to take a really long time on my macbook too.

These two tests have been running for more than one hour now.

**Comment by sveitser** [comment]
They don't seem to complete on my macbook either.

**Comment by philippecamacho** [comment]
So based on the [discussion](https://espresso.zulipchat.com/#narrow/stream/398121-Optimism/topic/Ongoing.20status/near/380375007), should we ignore the op-e2e tests and merge this PR?

**Comment by nyospe** [comment]
See this conversation. We can just ignore the pnpm tests.

https://espressosys.slack.com/archives/C05C8QK5BPX/p1690577359314929

**Review by nyospe — APPROVED** [review]
Helpful.

**Pull request merged**
